modLoader = "javafml" #mandatory
loaderVersion = "[39,)" #mandatory
license = "MIT"
issueTrackerURL = "https://github.com/Yamahari/ILikeWood-BiomesOPlenty-Plugin/issues" #optional

[[mods]] #mandatory
modId = "ilikewoodxbiomesoplenty" #mandatory
version = "1.18.1-7.0.0.0" #mandatory
displayName = "I Like Wood - Biomes o' Plenty Plugin" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/i-like-wood-biomes-o-plenty-plugin" #optional
logoFile = "logo.png" #optional
credits = "Yamahari and the people of Forge" #optional
authors = "Yamahari" #optional
description = '''
Adds Biomes o' Plenty support for I Like Wood.
'''

[[dependencies.ilikewoodxbiomesoplenty]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[39.0.9,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewoodxbiomesoplenty]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewoodxbiomesoplenty]]
modId = "ilikewood"
mandatory = true
versionRange = "[1.18.1-7.0.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewoodxbiomesoplenty]]
modId = "biomesoplenty"
mandatory = true
versionRange = "[1.18.1-15.0.0.51,)"
ordering = "NONE"
side = "BOTH"