modLoader = "javafml"
loaderVersion = "${version_range_loader}"
license = "MIT"
issueTrackerURL = "https://github.com/Yamahari/ILikeWood-BiomesOPlenty-Plugin/issues"

[[mods]]
modId = "ilikewoodxbiomesoplenty"
version = "${version}"
displayName = "I Like Wood - Biomes o' Plenty Plugin"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/i-like-wood-biomes-o-plenty-plugin"
logoFile = "logo.png"
credits = "Yamahari and the people of Forge"
authors = "Yamahari"
description = '''
Adds Biomes o' Plenty support for I Like Wood.
'''

[[dependencies.ilikewoodxbiomesoplenty]]
modId = "forge"
mandatory = true
versionRange = "${version_range_forge}"
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewoodxbiomesoplenty]]
modId = "minecraft"
mandatory = true
versionRange = "${version_range_mc}"
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewoodxbiomesoplenty]]
modId = "ilikewood"
mandatory = true
versionRange = "${version_range_ilw}"
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewoodxbiomesoplenty]]
modId = "biomesoplenty"
mandatory = true
versionRange = "${version_range_bop}"
ordering = "NONE"
side = "BOTH"