modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory
license = "MIT"
issueTrackerURL = "https://github.com/Yamahari/ILikeWood-BiomesOPlenty-Plugin/issues" #optional

[[mods]] #mandatory
modId = "ilikewoodxbiomesoplenty" #mandatory
version = "1.16.5-6.2.2.0" #mandatory
displayName = "I Like Wood - Biomes o' Plenty Plugin" #mandatory
updateJSONURL = "http://myurl.me/" #optional
displayURL = "http://example.com/" #optional
logoFile = "logo.png" #optional
credits = "Yamahari and the people of Forge" #optional
authors = "Yamahari" #optional
description = '''
Adds Biomes o' Plenty support for I Like Wood.
'''

[[dependencies.ilikewoodxbiomesoplenty]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewoodxbiomesoplenty]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewoodxbiomesoplenty]]
modId = "ilikewood"
mandatory = true
versionRange = "[1.16.5-6.2.2.0,)"
ordering = "NONE"
side = "BOTH"